fs: Simplify struct BDFSInfo
Turned out this was a private struct and these two static-const-array
cross-references were not really needed.

generic.c:185:52: error: initializer element is not a compile-time constant
      .mkfs_options = fs_features[BD_FS_TECH_EXT2].mkfs,
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
generic.c:187:51: error: initializer element is not a compile-time constant
      .resize_mode = fs_features[BD_FS_TECH_EXT2].resize,
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~